### ISSUE TITLE
Vérification du placement des mines

### ISSUE THREAD

**Issue by AitOuaretSalas** [UEVE-DLL-2024-2025/DLL#22]
Dans la méthode __placer_mines, on place les mines aléatoirement, mais il n'y avait pas de vérification pour éviter de placer une mine sur une case qui en contient déjà une. Il faut donc ajouter cette vérification

**Comment by samy-FERGUI** [comment]
@AitOuaretSalas  c'est bien l'issue #3, @Marwane-20 a déjà fait un PR #15

**Comment by SMoraisDev** [comment]
Comme l'a indiqué @samy-FERGUI, c'est un duplicat d'issue. Je ferme celle là :)
