### ISSUE TITLE
Afficher le nombre de cases restantes à découvrir

### ISSUE THREAD

**Issue by mariatouil** [UEVE-DLL-2024-2025/DLL#55]
**comportement actuel :**
Le joueur n’a pas d’indication sur le nombre de cases qu’il doit encore découvrir pour gagner la partie. Cela rend difficile de suivre sa progression.

**Solution proposée :**
Ajouter un compteur visible qui affiche en temps réel le nombre de cases encore non découvertes. Ce compteur doit :
Être mis à jour à chaque tour (après chaque action du joueur).
Réduire le nombre à chaque fois qu’une case est découverte.

<img width="525" alt="image" src="https://github.com/user-attachments/assets/e054a172-7f05-4b26-b36d-7022d4792e2b">

**Comment by SMoraisDev** [comment]
Doublon de #47
